"""Pre-canned maintenance task templates for Home Maintenance integration."""

from __future__ import annotations

TASK_TEMPLATES: list[dict] = [
    # -------------------------------------------------------------------------
    # HVAC
    # -------------------------------------------------------------------------
    {
        "category": "HVAC",
        "title": "Change HVAC filter",
        "description": "Replace the HVAC air filter to maintain air quality and system efficiency.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:air-filter",
    },
    {
        "category": "HVAC",
        "title": "Clean air vents",
        "description": "Remove dust and debris from air vents and registers throughout the home.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:air-filter",
    },
    {
        "category": "HVAC",
        "title": "Inspect ductwork",
        "description": "Check ductwork for leaks, damage, or disconnected sections.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:hvac",
    },
    {
        "category": "HVAC",
        "title": "Service AC unit",
        "description": "Schedule professional service for the air conditioning unit including refrigerant check.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:hvac",
    },
    {
        "category": "HVAC",
        "title": "Check thermostat calibration",
        "description": "Verify thermostat reads the correct temperature and adjust if needed.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:thermometer",
    },
    {
        "category": "HVAC",
        "title": "Bleed radiators",
        "description": "Release trapped air from radiators to improve heating efficiency.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:thermometer",
    },
    {
        "category": "HVAC",
        "title": "Clean condensate drain line",
        "description": "Flush the AC condensate drain line with vinegar to prevent clogs.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:hvac",
    },
    # -------------------------------------------------------------------------
    # Plumbing
    # -------------------------------------------------------------------------
    {
        "category": "Plumbing",
        "title": "Check for leaks under sinks",
        "description": "Inspect under all sinks for signs of leaks, drips, or water damage.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:pipe",
    },
    {
        "category": "Plumbing",
        "title": "Flush water heater",
        "description": "Drain and flush the water heater to remove sediment buildup.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:water-pump",
    },
    {
        "category": "Plumbing",
        "title": "Clean faucet aerators",
        "description": "Remove and clean faucet aerators to restore water flow and remove mineral deposits.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:faucet",
    },
    {
        "category": "Plumbing",
        "title": "Test sump pump",
        "description": "Pour water into the sump pit to verify the pump activates and drains properly.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:water-pump",
    },
    {
        "category": "Plumbing",
        "title": "Inspect washing machine hoses",
        "description": "Check washing machine supply hoses for bulges, cracks, or leaks.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:pipe",
    },
    {
        "category": "Plumbing",
        "title": "Clean garbage disposal",
        "description": "Clean and deodorize the garbage disposal with ice and citrus peels.",
        "interval_value": 7,
        "interval_type": "days",
        "icon": "mdi:pipe",
    },
    {
        "category": "Plumbing",
        "title": "Check toilet components",
        "description": "Inspect toilet flappers, fill valves, and supply lines for wear or leaks.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:pipe",
    },
    # -------------------------------------------------------------------------
    # Electrical
    # -------------------------------------------------------------------------
    {
        "category": "Electrical",
        "title": "Test GFCI outlets",
        "description": "Press the test and reset buttons on all GFCI outlets to verify they trip properly.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:power-plug",
    },
    {
        "category": "Electrical",
        "title": "Check electrical panel",
        "description": "Inspect the electrical panel for signs of corrosion, overheating, or loose connections.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:lightning-bolt",
    },
{
        "category": "Electrical",
        "title": "Replace smoke detector batteries",
        "description": "Replace batteries in all smoke detectors even if they have not chirped.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:lightning-bolt",
    },
    {
        "category": "Electrical",
        "title": "Test carbon monoxide detectors",
        "description": "Test all carbon monoxide detectors to confirm they are functioning correctly.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:lightning-bolt",
    },
    {
        "category": "Electrical",
        "title": "Inspect extension cords",
        "description": "Check all extension cords for fraying, damage, or overloading.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:power-plug",
    },
    # -------------------------------------------------------------------------
    # Exterior
    # -------------------------------------------------------------------------
    {
        "category": "Exterior",
        "title": "Clean gutters",
        "description": "Remove leaves and debris from gutters and downspouts to prevent water damage.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:home-roof",
    },
    {
        "category": "Exterior",
        "title": "Inspect roof",
        "description": "Check roof for missing, damaged, or curling shingles and signs of wear.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:home-roof",
    },
    {
        "category": "Exterior",
        "title": "Power wash siding",
        "description": "Power wash the exterior siding to remove dirt, mold, and mildew.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:home-roof",
    },
    {
        "category": "Exterior",
        "title": "Check caulking around windows",
        "description": "Inspect and replace deteriorated caulking around windows and door frames.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:home-roof",
    },
    {
        "category": "Exterior",
        "title": "Inspect foundation",
        "description": "Walk around the foundation looking for cracks, settling, or water intrusion.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:home-roof",
    },
    {
        "category": "Exterior",
        "title": "Clean dryer vent",
        "description": "Clean the exterior dryer vent duct to prevent lint buildup and fire hazard.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:home-roof",
    },
    {
        "category": "Exterior",
        "title": "Seal driveway cracks",
        "description": "Fill and seal cracks in the driveway to prevent water damage and further deterioration.",
        "interval_value": 24,
        "interval_type": "months",
        "icon": "mdi:fence",
    },
    # -------------------------------------------------------------------------
    # Interior
    # -------------------------------------------------------------------------
    {
        "category": "Interior",
        "title": "Deep clean carpets",
        "description": "Steam clean or shampoo all carpeted areas to remove deep dirt and allergens.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:sofa",
    },
    {
        "category": "Interior",
        "title": "Clean range hood filter",
        "description": "Remove and clean the range hood grease filter in hot soapy water.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:wall-sconce-flat",
    },
    {
        "category": "Interior",
        "title": "Recaulk bathroom",
        "description": "Remove old caulk and apply fresh caulk around bathtub, shower, and sink edges.",
        "interval_value": 60,
        "interval_type": "months",
        "icon": "mdi:wall-sconce-flat",
    },
    {
        "category": "Interior",
        "title": "Check window locks",
        "description": "Test all window locks and latches to ensure they engage properly.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:wall-sconce-flat",
    },
    {
        "category": "Interior",
        "title": "Clean drains",
        "description": "Clear slow drains using a drain snake or enzyme-based cleaner.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:sofa",
    },
    {
        "category": "Interior",
        "title": "Lubricate door hinges",
        "description": "Apply lubricant to all door hinges to eliminate squeaks and ensure smooth operation.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:wall-sconce-flat",
    },
    # -------------------------------------------------------------------------
    # Appliances
    # -------------------------------------------------------------------------
    {
        "category": "Appliances",
        "title": "Clean dishwasher",
        "description": "Run an empty cycle with dishwasher cleaner and wipe down the door seal.",
        "interval_value": 60,
        "interval_type": "days",
        "icon": "mdi:dishwasher",
    },
    {
        "category": "Appliances",
        "title": "Clean washing machine",
        "description": "Run a cleaning cycle with washing machine cleaner and wipe the gasket.",
        "interval_value": 60,
        "interval_type": "days",
        "icon": "mdi:washing-machine",
    },
    {
        "category": "Appliances",
        "title": "Clean refrigerator coils",
        "description": "Vacuum or brush the condenser coils on the refrigerator to maintain efficiency.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:dishwasher",
    },
    {
        "category": "Appliances",
        "title": "Replace water filter",
        "description": "Replace the refrigerator water filter cartridge for clean drinking water.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:dishwasher",
    },
    {
        "category": "Appliances",
        "title": "Clean oven",
        "description": "Run the self-clean cycle or manually clean the oven interior.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:dishwasher",
    },
    {
        "category": "Appliances",
        "title": "Defrost freezer",
        "description": "Defrost the freezer if ice buildup exceeds a quarter inch.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:dishwasher",
    },
    {
        "category": "Appliances",
        "title": "Clean dryer lint trap deep",
        "description": "Remove the lint screen and vacuum the lint trap housing to improve airflow.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:washing-machine",
    },
    # -------------------------------------------------------------------------
    # Safety
    # -------------------------------------------------------------------------
    {
        "category": "Safety",
        "title": "Test smoke detectors",
        "description": "Press the test button on every smoke detector and replace any that fail.",
        "interval_value": 30,
        "interval_type": "days",
        "icon": "mdi:shield-home",
    },
    {
        "category": "Safety",
        "title": "Check fire extinguisher pressure",
        "description": "Verify the pressure gauge on each fire extinguisher is in the green zone.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:fire-extinguisher",
    },
    {
        "category": "Safety",
        "title": "Review emergency plan",
        "description": "Review and update the household emergency plan with all family members.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:shield-home",
    },
    {
        "category": "Safety",
        "title": "Test security system",
        "description": "Run a full test of the home security system including all sensors and alarms.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:shield-home",
    },
    {
        "category": "Safety",
        "title": "Check first aid kit",
        "description": "Inspect the first aid kit and replace any expired or used supplies.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:shield-home",
    },
    {
        "category": "Safety",
        "title": "Inspect fire escape routes",
        "description": "Walk through all fire escape routes and ensure exits are clear and accessible.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:fire-extinguisher",
    },
    # -------------------------------------------------------------------------
    # Lawn & Garden
    # -------------------------------------------------------------------------
    {
        "category": "Lawn & Garden",
        "title": "Mow lawn",
        "description": "Mow the lawn to the recommended height for the grass type.",
        "interval_value": 7,
        "interval_type": "days",
        "icon": "mdi:grass",
    },
    {
        "category": "Lawn & Garden",
        "title": "Fertilize lawn",
        "description": "Apply seasonal fertilizer to the lawn following product instructions.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:grass",
    },
    {
        "category": "Lawn & Garden",
        "title": "Sharpen mower blades",
        "description": "Remove and sharpen or replace lawn mower blades for a clean cut.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:grass",
    },
    {
        "category": "Lawn & Garden",
        "title": "Prune shrubs",
        "description": "Trim and shape shrubs and hedges to maintain appearance and plant health.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:flower",
    },
    {
        "category": "Lawn & Garden",
        "title": "Aerate lawn",
        "description": "Aerate the lawn to reduce soil compaction and improve root growth.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:grass",
    },
    {
        "category": "Lawn & Garden",
        "title": "Clean outdoor furniture",
        "description": "Wash and treat outdoor furniture to remove dirt, mold, and weather damage.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:flower",
    },
    {
        "category": "Lawn & Garden",
        "title": "Inspect irrigation system",
        "description": "Check sprinkler heads, drip lines, and timers for proper operation.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:grass",
    },
    # -------------------------------------------------------------------------
    # Seasonal
    # -------------------------------------------------------------------------
    {
        "category": "Seasonal",
        "title": "Winterize outdoor faucets",
        "description": "Disconnect hoses, drain outdoor faucets, and install insulated covers.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:snowflake",
    },
    {
        "category": "Seasonal",
        "title": "Service snow blower",
        "description": "Change oil, check belts, and test the snow blower before winter arrives.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:snowflake",
    },
    {
        "category": "Seasonal",
        "title": "Reverse ceiling fan direction",
        "description": "Switch ceiling fan rotation direction for the current season.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:white-balance-sunny",
    },
    {
        "category": "Seasonal",
        "title": "Check weather stripping",
        "description": "Inspect and replace worn weather stripping around doors and windows.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:snowflake",
    },
    {
        "category": "Seasonal",
        "title": "Store or retrieve seasonal items",
        "description": "Rotate seasonal items in and out of storage as the season changes.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:white-balance-sunny",
    },
    {
        "category": "Seasonal",
        "title": "Test outdoor lighting",
        "description": "Check all exterior lights, replace bulbs, and clean fixtures.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:white-balance-sunny",
    },
    {
        "category": "Seasonal",
        "title": "Inspect attic insulation",
        "description": "Check attic insulation for settling, moisture, or pest damage before winter.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:snowflake",
    },
    {
        "category": "Seasonal",
        "title": "Clean window screens",
        "description": "Remove window screens, wash with soapy water, and reinstall.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:white-balance-sunny",
    },
    # -------------------------------------------------------------------------
    # Garage & Vehicles
    # -------------------------------------------------------------------------
    {
        "category": "Garage & Vehicles",
        "title": "Lubricate garage door",
        "description": "Apply lubricant to garage door tracks, rollers, hinges, and springs.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:garage",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Test garage door auto-reverse",
        "description": "Place an object under the garage door and verify it reverses when closing.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:garage",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Check garage door weather seal",
        "description": "Inspect the bottom seal and side weather stripping on the garage door.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:garage",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Organize garage storage",
        "description": "Declutter the garage, check for expired chemicals, and reorganize storage.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:garage",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Check vehicle tire pressure",
        "description": "Check and adjust tire pressure on all vehicles to the recommended PSI.",
        "interval_value": 30,
        "interval_type": "days",
        "icon": "mdi:car",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Rotate vehicle tires",
        "description": "Rotate tires to ensure even wear and extend tire life.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:car",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Change engine oil",
        "description": "Change engine oil and oil filter per manufacturer recommendations.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:car",
    },
    {
        "category": "Garage & Vehicles",
        "title": "Replace windshield wipers",
        "description": "Replace windshield wiper blades when streaking or skipping.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:car",
    },
    # -------------------------------------------------------------------------
    # Pool & Spa
    # -------------------------------------------------------------------------
    {
        "category": "Pool & Spa",
        "title": "Test pool water chemistry",
        "description": "Test pool pH, chlorine, alkalinity, and calcium hardness levels.",
        "interval_value": 7,
        "interval_type": "days",
        "icon": "mdi:pool",
    },
    {
        "category": "Pool & Spa",
        "title": "Clean pool filter",
        "description": "Backwash or clean the pool filter cartridge to maintain proper filtration.",
        "interval_value": 30,
        "interval_type": "days",
        "icon": "mdi:pool",
    },
    {
        "category": "Pool & Spa",
        "title": "Skim and vacuum pool",
        "description": "Skim debris from the surface and vacuum the pool floor.",
        "interval_value": 7,
        "interval_type": "days",
        "icon": "mdi:pool",
    },
    {
        "category": "Pool & Spa",
        "title": "Inspect pool pump and motor",
        "description": "Check pool pump for leaks, unusual noise, and proper pressure readings.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:pool",
    },
    {
        "category": "Pool & Spa",
        "title": "Shock treat pool",
        "description": "Add pool shock treatment to eliminate bacteria and restore water clarity.",
        "interval_value": 14,
        "interval_type": "days",
        "icon": "mdi:pool",
    },
    {
        "category": "Pool & Spa",
        "title": "Clean spa filter",
        "description": "Remove, rinse, and deep clean the hot tub or spa filter cartridge.",
        "interval_value": 30,
        "interval_type": "days",
        "icon": "mdi:hot-tub",
    },
    {
        "category": "Pool & Spa",
        "title": "Drain and refill spa",
        "description": "Drain the hot tub completely, clean the shell, and refill with fresh water.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:hot-tub",
    },
    # -------------------------------------------------------------------------
    # Pest Control
    # -------------------------------------------------------------------------
    {
        "category": "Pest Control",
        "title": "Inspect for termites",
        "description": "Check foundation, wood structures, and crawl spaces for signs of termite activity.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:bug",
    },
    {
        "category": "Pest Control",
        "title": "Refresh ant and roach bait stations",
        "description": "Replace indoor and outdoor pest bait stations with fresh bait.",
        "interval_value": 90,
        "interval_type": "days",
        "icon": "mdi:bug",
    },
    {
        "category": "Pest Control",
        "title": "Seal entry points",
        "description": "Inspect and seal gaps around pipes, vents, and the foundation where pests can enter.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:bug",
    },
    {
        "category": "Pest Control",
        "title": "Check attic for rodents",
        "description": "Inspect attic for droppings, nesting materials, or chewed wiring from rodents.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:bug",
    },
    {
        "category": "Pest Control",
        "title": "Clean bird feeders",
        "description": "Disassemble and scrub bird feeders to prevent mold and disease spread.",
        "interval_value": 14,
        "interval_type": "days",
        "icon": "mdi:bird",
    },
    # -------------------------------------------------------------------------
    # Water Treatment
    # -------------------------------------------------------------------------
    {
        "category": "Water Treatment",
        "title": "Replace whole-house water filter",
        "description": "Replace the sediment and carbon filter cartridges in the whole-house water filtration system.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:water",
    },
    {
        "category": "Water Treatment",
        "title": "Add salt to water softener",
        "description": "Check and refill salt in the water softener brine tank.",
        "interval_value": 60,
        "interval_type": "days",
        "icon": "mdi:water",
    },
    {
        "category": "Water Treatment",
        "title": "Clean water softener brine tank",
        "description": "Empty, scrub, and refill the brine tank to remove salt bridges and sediment.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:water",
    },
    {
        "category": "Water Treatment",
        "title": "Replace reverse osmosis filters",
        "description": "Replace pre-filter, post-filter, and membrane in the RO drinking water system.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:water",
    },
    {
        "category": "Water Treatment",
        "title": "Test well water quality",
        "description": "Send a water sample to a lab for bacteria, nitrates, and mineral testing.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:water",
    },
    # -------------------------------------------------------------------------
    # Fireplace & Chimney
    # -------------------------------------------------------------------------
    {
        "category": "Fireplace & Chimney",
        "title": "Schedule chimney sweep",
        "description": "Hire a professional to clean the chimney flue and remove creosote buildup.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:fireplace",
    },
    {
        "category": "Fireplace & Chimney",
        "title": "Inspect chimney cap and flashing",
        "description": "Check the chimney cap for damage and inspect flashing for gaps or rust.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:fireplace",
    },
    {
        "category": "Fireplace & Chimney",
        "title": "Clean fireplace firebox",
        "description": "Remove ash buildup from the firebox and inspect firebrick for cracks.",
        "interval_value": 30,
        "interval_type": "days",
        "icon": "mdi:fireplace",
    },
    {
        "category": "Fireplace & Chimney",
        "title": "Check fireplace damper",
        "description": "Open and close the fireplace damper to ensure it moves freely and seals properly.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:fireplace",
    },
    # -------------------------------------------------------------------------
    # Septic System
    # -------------------------------------------------------------------------
    {
        "category": "Septic System",
        "title": "Pump septic tank",
        "description": "Schedule professional septic tank pumping to prevent overflow and drain field damage.",
        "interval_value": 36,
        "interval_type": "months",
        "icon": "mdi:water-pump",
    },
    {
        "category": "Septic System",
        "title": "Inspect septic drain field",
        "description": "Walk the drain field area checking for wet spots, odors, or lush grass patches.",
        "interval_value": 180,
        "interval_type": "days",
        "icon": "mdi:water-pump",
    },
    {
        "category": "Septic System",
        "title": "Add septic treatment",
        "description": "Add enzyme-based septic treatment to maintain healthy bacteria levels in the tank.",
        "interval_value": 30,
        "interval_type": "days",
        "icon": "mdi:water-pump",
    },
    # -------------------------------------------------------------------------
    # Painting & Finishes
    # -------------------------------------------------------------------------
    {
        "category": "Painting & Finishes",
        "title": "Touch up interior paint",
        "description": "Inspect walls for scuffs, nail holes, and chips. Touch up with matching paint.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:format-paint",
    },
    {
        "category": "Painting & Finishes",
        "title": "Inspect exterior paint",
        "description": "Check exterior paint for peeling, cracking, or fading and schedule repainting if needed.",
        "interval_value": 365,
        "interval_type": "days",
        "icon": "mdi:format-paint",
    },
    {
        "category": "Painting & Finishes",
        "title": "Refinish deck or porch",
        "description": "Sand, stain, or seal the deck or porch to protect wood from weather damage.",
        "interval_value": 24,
        "interval_type": "months",
        "icon": "mdi:format-paint",
    },
    {
        "category": "Painting & Finishes",
        "title": "Seal grout lines",
        "description": "Apply grout sealer to tile floors, backsplash, and shower areas to prevent staining.",
        "interval_value": 24,
        "interval_type": "months",
        "icon": "mdi:format-paint",
    },
]
